name: buddthist_date_time_and_date_picker
description: "A package build for convert date and time to buddhist year and buildin date picker"
version: 1.0.0
repository: https://github.com/genss333/buddthist_date_time.git

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  flutter_rounded_date_picker: ^3.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec


